# This moderate-level config uses the GPU 
# to compress 3 RGB streams in parallel

# Video parameters
videoFolder: "G:/videos/ncam/test6_240s_40fps/"
videoFilename: "0.mp4"
frameRate: 40
recTimeInSec: 240

# Camera parameters
numCams: 6
cameraSelection: [1,2,3,4,5,6]
cameraNames: ["Camera1","Camera2","Camera3", "Camera4","Camera5","Camera6"]
cameraMake: "flir"
cameraSettings: "./configs/rgb24.pfs"
pixelFormatInput: "bayer_bggr8" #"rgb24"
pixelFormatOutput: "rgb0"
frameWidth:  2816 #2688 #1152 #3168 #2304 #1280
frameHeight: 1664 #1536 #1024 #2176 #2048 #1024
offsetX: 128 #400
offsetY: 368 #100


# Flir settings
bufferSize: 1500
cameraExposureTimeInUs: 3582 #11638
cameraGain: 10.4
disableGamma: False #True
cameraDebug: False #True
ADCBits: "8"
printWriteQueue: 500
packetDelay: 500
MaxIncompleteImages: 200

# Compression parameters
gpuID: [0,0,0,0,0,0]                              
gpuMake: "nvidia"                     # "nvidia", "amd", "intel"                  
codec: "h264"                         # "h264", "h265", or user-defined video codec
quality: 21                           # 0-55
ffmpegLogLevel: "info"               # "quiet", "warning", "info"
# ffmpegPath: "/usr/bin/ffmpeg"       # Location of ffmpeg binary if not using Anaconda

# Display parameters
chunkLengthInSec: 5 #30
displayFrameRate: -5 #10

# Trigger Parameters
triggerController: 'arduino' #"None"
startArduino: True
serialPort: "COM3"                    # e.g. "COM3" Win; "/dev/ttyACM0" Linux
digitalPins: [9]
cameraTrigger: "Line2"

