# This moderate-level config uses the GPU 
# to compress 3 RGB streams in parallel

# Video parameters
videoFolder: "G:/Videos/3cam/testalt3/"
videoFilename: "2.mp4"
frameRate: 72 #60
recTimeInSec: 300 #1800 #600

# Camera parameters
numCams: 3
cameraSelection: [1,2,3]
cameraNames: ["Camera1","Camera2","Camera3"]
cameraMake: "flir"
cameraSettings: "./configs/rgb24.pfs"
pixelFormatInput: "bayer_bggr8" #"bayer_bggr8" #"rgb24" #
pixelFormatOutput: "rgb0"
frameWidth:  2688 #2688 #2560 #2304 #2048 #1792 #1536 #3072 #3200 #1536 #1152 #3184 #2304 #1280 #Max = 3208
frameHeight: 1536 #1536 #1792 #1792 #1536 #1280 #1024 #2048 #2176 #1408 #1024 #2160 #2048 #1024 #Max = 2200
offsetX: 128 #400
offsetY: 368 #100


# Flir settings
bufferSize: 1800
cameraExposureTimeInUs: 3582
cameraGain: 10.1
disableGamma: False #True
cameraDebug: True
ADCBits: "12"
printWriteQueue: 500
packetDelay: 500
MaxIncompleteImages: 200

# Compression parameters
gpuID: [0, 0, 0]                              
gpuMake: "nvidia"                     # "nvidia", "amd", "intel"                  
codec: "h264"                         # "h264", "h265", or user-defined video codec
quality: 21                           # 0-55
ffmpegLogLevel: "warning"               # "quiet", "warning", "info"
# ffmpegPath: "/usr/bin/ffmpeg"       # Location of ffmpeg binary if not using Anaconda

# Display parameters
chunkLengthInSec: 5 #30
displayFrameRate: 5 #10
displayDownsample: 4

# Trigger Parameters
triggerController: 'arduino' # "None" # 
startArduino: True
serialPort: "COM3"                    # e.g. "COM3" Win; "/dev/ttyACM0" Linux
digitalPins: [9]
cameraTrigger: "Line2"

