# This moderate-level config uses the GPU 
# to compress 3 RGB streams in parallel

# Video parameters
videoFolder: "D:/videos/6cam/test3/"
videoFilename: "0.mp4"
frameRate: 100
recTimeInSec: 300

# Camera parameters
numCams: 5
cameraSelection: [1,2,3,4,5]
cameraNames: ["Camera1","Camera2","Camera3", "Camera4","Camera5"] #"Camera6"]
cameraMake: "flir"
cameraSettings: "./configs/rgb24.pfs"
pixelFormatInput: "rgb24" 
pixelFormatOutput: "rgb0"
frameWidth: 1152 #3168 #2304 #1280
frameHeight: 1024 #2176 #2048 #1024
offsetX: 72 #400
offsetY: 64 #100


# Flir settings
bufferSize: 1500
cameraExposureTimeInUs: 3582 #11638
cameraGain: 10.4
disableGamma: False #True
cameraDebug: True
ADCBits: "8"
printWriteQueue: 500
packetDelay: 500
MaxIncompleteImages: 200

# Compression parameters
gpuID: [0,0,0,0,0] #,0]                              
gpuMake: "nvidia"                     # "nvidia", "amd", "intel"                  
codec: "h264"                         # "h264", "h265", or user-defined video codec
quality: 21                           # 0-55
ffmpegLogLevel: "warning"               # "quiet", "warning", "info"
# ffmpegPath: "/usr/bin/ffmpeg"       # Location of ffmpeg binary if not using Anaconda

# Display parameters
chunkLengthInSec: 5 #30
displayFrameRate: 5 #10

# Trigger Parameters
triggerController: 'arduino' #"None"
startArduino: True
serialPort: "COM3"                    # e.g. "COM3" Win; "/dev/ttyACM0" Linux
digitalPins: [9]
cameraTrigger: "Line2"

